### ISSUE TITLE
Features request: Gather all folders in a hidden folder

### ISSUE THREAD

**Issue by LAfricain** [FreeHealth/freehealth#116]
Currently I can see almost 3 folders in the $HOME, freehealth, drugs, icd10. I think it would be safer (and cleaner) to put all this in a hidden folder ".freehealth".

**Comment by jeromecc** [comment]
Why would it be safer?
FreeHealth, like FreeMedForms, is a collection of apps. You have the EHR (FreeHealth EHR), the prescription app (which should be renamed FreeRx to avoid confusion with FreeMedForms project app called FreeDiams) and the ICD component. They are packaged separately and can be installed on their own, so they need their own hidden folder in ~.

**Comment by LAfricain** [comment]
Ok I understand, but it should be better to be hidden folders or to be in "Documents" folder. I think hidden is more safe, people can delete it as quickly as a non hidden folder. (It's just my opinion).
